import turtle
quad=turtle.Turtle()
for i in range(4):
    quad.fd(100)
    quad.rt(90)
quad.clear()
pent=turtle.Turtle()
for i in range(5):
    pent.fd(100)
    pent.rt(72)
pent.clear()
estr=turtle.Turtle()
for i in range(5):
    estr.fd(100)
    estr.rt(144)
estr.clear()
qestr=turtle.Turtle()
for i in range(4):
    for i in range(5):
        qestr.fd(50)
        qestr.rt(144)
    qestr.penup()
    qestr.fd(150)
    qestr.rt(90)
    qestr.pendown()
qestr.clear()
testr=turtle.Turtle()
for i in range(3):
    for i in range(5):
        testr.fd(50)
        testr.rt(144)
    testr.penup()
    testr.fd(150)
    testr.pendown()
    testr.rt(120)
testr.lt(90)
testr.penup()
testr.fd(100)
testr.pendown()
testr.fd(50)
testr.clear() 
circ=turtle.Turtle()
#for i in range(360):
    #circ.fd(50)
    #circ.bk(50)
    #circ.rt(1)
circ.color("yellow")
circ.begin_fill()
circ.fillcolor("yellow")
circ.circle(50)
circ.end_fill()
circ.clear()
lua=turtle.Turtle()
lua.color("yellow")
for i in range(3):
    for i in range(5):
        lua.fd(50)
        lua.rt(144)
    lua.penup()
    lua.fd(150)
    lua.pendown()
    lua.rt(120)
lua.lt(90)
lua.penup()
lua.fd(100)
lua.pendown()
for i in range(360):
    lua.rt(1)
    lua.fd(50)
    lua.bk(50)
lua.color("black")
lua.rt(120)
lua.fd(20)
for i in range(360):
    lua.rt(1)
    lua.fd(50)
    lua.bk(50)
lua.clear()

