import turtle
t=turtle.Turtle()
jn=turtle.Screen()
def f1():
    t.begin_fill()
    t.fillcolor("blue")
    t.color("blue")
    t.circle(200)
    t.rt(90)
    t.bk(200)
    t.end_fill()
def f2():
    t.begin_fill()
    t.fillcolor("white")
    t.color("white")
    t.circle(180)
    t.end_fill()
def f3():
    t.penup()
    t.fd(300)
    t.pendown()
    t.color("blue")
    for i in range(5):
        t.fd(100)
        t.rt(144)
from musicav1 import *
def f4():
    Do.toca(0.5)
    sleep(0.01)
    Do.toca(0.5)
    Sol.toca(0.5)
    sleep(0.01)
    Sol.toca(0.5)
    La.toca(0.5)
    sleep(0.01)
    La.toca(0.5)
    Sol.toca(1)
    Fa.toca(0.5)
    sleep(0.01)
    Fa.toca(0.5)
    Mi.toca(0.5)
    sleep(0.01)
    Mi.toca(0.5)
    Re.toca(0.5)
    sleep(0.01)
    Re.toca(0.5)
    Do.toca(1)
def f5():
    Sol.toca(0.5)
    sleep(0.01)
    Sol.toca(0.5)
    Fa.toca(0.5)
    sleep(0.01)
    Fa.toca(0.5)
    Mi.toca(0.5)
    sleep(0.01)
    Mi.toca(0.5)
    Re.toca(1)
f1()
f2()
f3()
f4()
f5()
f5()
f4()